### ISSUE TITLE
Building on OSx  - Fatal Error

### ISSUE THREAD

**Issue by JeanHuit** [NibbleIT/nate#6]
Building on OSX provides a fatal error. Due to inability to generate icon package for windows and linux. 

"
Fatal error: Error while updating the Windows icon. Wine (winehq.org) must be installed to add custom icons from Mac and Linux.
"
No Wine binary for OSX

**Comment by JahlomP** [comment]
before building, update the gruntfile to include on mac as build target https://github.com/NibbleIT/nate/blob/master/Gruntfile.js#L16

**Comment by JeanHuit** [comment]
Solution:

Install Homebrew
Using Homebrew to install "brew install wine"

This issue raised should sort any error on fontconfig during the wine installation.
