### ISSUE TITLE
How do I start? 

### ISSUE THREAD

**Issue by Ganyobi** [NibbleIT/nate#7]
Am interested in working on this project, kindly direct me on resources that will help me get started.

**Comment by JahlomP** [comment]
For NW.js, go to https://github.com/nwjs/nw.js/wiki.
For Codemirrror, go to https://codemirror.net/doc/manual.html.

If you need any help, go to https://groups.google.com/forum/#!topic/nwjs-general/BXAlYaD-CPA.

I will close this for now.

**Comment by JahlomP** [comment]
Sorry I linked you to a different group. This is the right one https://groups.google.com/forum/#!forum/nateeditor
